/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fos.Client.Admin;

import Fos.FosInterface;
import java.rmi.Naming;
import java.util.Arrays;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author User
 */
public class Report extends javax.swing.JFrame {
    /**
     * Creates new form Report
     */
//    private DefaultPieDataset pieDataset;
//    private JFreeChart pieChart;
//    private PiePlot piePlot;
//    private ChartPanel chartPanel;
    public Report() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        try{
            FosInterface dbi = (FosInterface)Naming.lookup("rmi://localhost:2000/Report");
            String[][] result = dbi.Report();
            System.out.println(Arrays.deepToString(result));
            
            for (String[] row : result) {
                for (String item : row) {
                    System.out.println(item);
                }
            }
            
            //age
            DefaultTableModel model = (DefaultTableModel) ageTable.getModel();
            String[][] rowsToAdd = {result[1], result[2], result[3]};

            for (String[] row : rowsToAdd) {
                Object[] rowData = new Object[]{row[0], row[1]}; 
                model.addRow(rowData);
            }
            
            //gender
            DefaultTableModel modelGender = (DefaultTableModel) genderTable.getModel();
            String[][] genderRows = {result[4], result[5]};

            for (String[] row : genderRows) {
                Object[] rowData1 = new Object[]{row[0], row[1]}; 
                modelGender.addRow(rowData1);
            }
            
            //revenue
            DefaultTableModel modelRevenue = (DefaultTableModel) revenueTable.getModel();
            String[][] revenueRows = {result[7], result[8], result[9]};

            for (String[] row : revenueRows) {
                Object[] rowData2 = new Object[]{row[0], row[1]}; 
                modelRevenue.addRow(rowData2);
            }
            
            //order
            DefaultTableModel modelOrder = (DefaultTableModel) orderTable.getModel();
            String[][] orderRows = {result[11], result[12], result[13]};

            for (String[] row : orderRows) {
                Object[] rowData3 = new Object[]{row[0], row[1]}; 
                modelOrder.addRow(rowData3);
            }
            txtTotalCus.setText(result[0][1]);
            txtTotalRevenue.setText("RM"+result[6][1]);
            txtTotalOrder.setText(result[10][1]);
        }catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTotalRevenue = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        revenueTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalCus = new javax.swing.JLabel();
        btnAgePie = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ageTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        genderTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalOrder = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 545));
        setPreferredSize(new java.awt.Dimension(920, 545));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 520));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ToTal revenue:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("details");
        jButton1.setBorderPainted(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 20));

        txtTotalRevenue.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTotalRevenue.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalRevenue.setText("RM19022.34");
        jPanel2.add(txtTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Top 3 Income Category:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        revenueTable.setBackground(new java.awt.Color(153, 255, 153));
        revenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(revenueTable);
        if (revenueTable.getColumnModel().getColumnCount() > 0) {
            revenueTable.getColumnModel().getColumn(0).setResizable(false);
            revenueTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, 80));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(440, 60, 420, 200);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Goudy Stout", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ToTal Customer:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtTotalCus.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTotalCus.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCus.setText("54");
        jPanel3.add(txtTotalCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnAgePie.setBackground(new java.awt.Color(153, 255, 153));
        btnAgePie.setText("details");
        btnAgePie.setBorderPainted(false);
        btnAgePie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgePieActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgePie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Top 3 Age Group:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        ageTable.setBackground(new java.awt.Color(153, 255, 153));
        ageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ageTable);
        if (ageTable.getColumnModel().getColumnCount() > 0) {
            ageTable.getColumnModel().getColumn(0).setResizable(false);
            ageTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 80));

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setText("details");
        jButton6.setBorderPainted(false);
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        genderTable.setBackground(new java.awt.Color(153, 255, 153));
        genderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(genderTable);
        if (genderTable.getColumnModel().getColumnCount() > 0) {
            genderTable.getColumnModel().getColumn(0).setResizable(false);
            genderTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, 60));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 60, 370, 420);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Goudy Stout", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ToTal Order:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtTotalOrder.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTotalOrder.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalOrder.setText("203");
        jPanel4.add(txtTotalOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setText("details");
        jButton4.setBorderPainted(false);
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Top 3 Total Order:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        orderTable.setBackground(new java.awt.Color(153, 255, 153));
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, 80));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(440, 270, 420, 210);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Report");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 10, 140, 44);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgePieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgePieActionPerformed
//        pieDataset = new DefaultPieDataset();
//        pieDataset.setValue('sw',new Double(9.1));
//        pieDataset.setValue('sww',new Double(9.1));
//        System.out.println("11");
//        pieDataset = new DefaultPieDataset();
//        pieDataset.setValue("One", new Integer(10));
//        pieDataset.setValue("Two", new Integer(20));
//        pieDataset.setValue("Three", new Integer(30));
//        pieDataset.setValue("Four", new Integer(10));
//        pieDataset.setValue("Five", new Integer(20));
//        pieDataset.setValue("Six", new Integer(10));
//        JFreeChart chart = ChartFactory.createPieChart3D("3D Pie Chart", pieDataset, true, true, false);
//
//        piePlot = (PiePlot) chart.getPlot();
//        chartPanel = new ChartPanel(chart);
//        jPanel1.removeAll();
//        jPanel1.add(chartPanel);
//        chartPanel.validate();


    }//GEN-LAST:event_btnAgePieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ageTable;
    private javax.swing.JButton btnAgePie;
    private javax.swing.JTable genderTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable revenueTable;
    private javax.swing.JLabel txtTotalCus;
    private javax.swing.JLabel txtTotalOrder;
    private javax.swing.JLabel txtTotalRevenue;
    // End of variables declaration//GEN-END:variables
}
