/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fos.Client.User;



import Fos.Client.Admin.Manage_Menu;
import Fos.FosInterface;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.rmi.Naming;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static Boolean saveDetails = false;

    public Login() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        
//        if (saveDetails){
//           crudentialCheck.setSelected(true);
//        }else{
//            crudentialCheck.setSelected(false);
//        }
        
        try (ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream("userCredentials.ser"))) {
            User storedUser = (User) inputStream.readObject();
            name.setText(storedUser.getUsername());
            password.setText(storedUser.getPassword());
            crudentialCheck.setSelected(true);
            saveDetails = true;
        } catch (Exception e) {
            System.out.println("Stored credentials not found. Proceed with regular login.");
        }
        validateFields();

    }
    
    public class User implements Serializable {
        private static final long serialVersionUID = 1L;

        private String username;
        private String password; // Password should be securely hashed
        // Other user attributes and methods as needed

        // Constructors, getters, setters, and other methods
        // ...

        // Example constructor
        public User(String username, String password) {
            this.username = username;
            this.password = password;
        }

        // Getter for username (you can add more getters for other attributes)
        public String getUsername() {
            return username;
        }

        // Getter for password (you can add more getters for other attributes)
        public String getPassword() {
            return password;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SignUp = new javax.swing.JButton();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crudentialCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 500));
        setPreferredSize(new java.awt.Dimension(920, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BB BreakFast");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 460));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp.setText("SignUp");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel3.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        login.setBackground(new java.awt.Color(0, 102, 102));
        login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel3.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 80, 30));

        password.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 320, 40));

        name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 320, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password : ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("UserName: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Don't have an account?");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Login");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        crudentialCheck.setBackground(new java.awt.Color(255, 255, 204));
        crudentialCheck.setText("Save UserName");
        crudentialCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudentialCheckActionPerformed(evt);
            }
        });
        jPanel3.add(crudentialCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    public void validateFields(){
        String nam = name.getText();
        String pass = password.getText();
        
        if (!nam.equals("") && !pass.equals(""))
            login.setEnabled(true);    
        else
            login.setEnabled(false);           
    }
    
    public void saveCrudentials(String nam, String pass){
        if (saveDetails){
            User user = new User(nam, pass);
            System.out.println(nam);
            try(ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream("userCredentials.ser")))  {

                outputStream.writeObject(user);     

            } catch (IOException e) {
                System.out.println(e.toString());
            }
        }else{
            File file = new File("userCredentials.ser");
            if (file.exists()) {
                if (file.delete()) {
                    System.out.println("Stored credentials deleted.");
                } else {
                    System.out.println("Failed to delete stored credentials.");
                }
            } else {
                System.out.println("Stored credentials file not found.");
            }
        }
        
        
    }
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
            String nam = name.getText();
            String pass = password.getText();
            FosInterface dbi = (FosInterface)Naming.lookup("rmi://localhost:2000/Login");
            
            String result = dbi.Login(nam,pass);
            System.out.println(result);
            if (null != result)switch (result) {
                case "userLogin":
                    saveCrudentials(nam,pass);
                    JOptionPane.showMessageDialog(null, "Login Successful! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                    Menu User = new Menu();
                    User.setVisible(true);
                    break;
                case "adminLogin":
                    saveCrudentials(nam,pass);
                    JOptionPane.showMessageDialog(null, "Login Successful! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                    Manage_Menu Admin = new Manage_Menu();
                    Admin.setVisible(true);
                    break;
                case "incorrect":
                    JOptionPane.showMessageDialog(null, "UserName or Password Incorrect! ", "Error", JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    break;
            }  
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        setVisible(false);
        SignUp Info = new SignUp();
        Info.setVisible(true);
    }//GEN-LAST:event_SignUpActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        validateFields();
    }//GEN-LAST:event_nameKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        validateFields();
    }//GEN-LAST:event_passwordKeyReleased

    private void crudentialCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudentialCheckActionPerformed
        if (saveDetails == false){
            saveDetails = true;
        }else{
            saveDetails = false;
        }
    }//GEN-LAST:event_crudentialCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUp;
    private javax.swing.JCheckBox crudentialCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
